version: "3.8"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: always
    container_name: quick-full-stack-app-backend
    image: quick-full-stack-app-backend
