name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker Image
      run: sudo docker pull amagdy9129/cicd-pipeline:latest
    - name: Delete Old Docker Container
      run: sudo docker rm -f cicd-pipeline-container
    - name: Run Docker Container
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_HOST: ${{ secrets.DB_HOST }}
      run: sudo docker run -e DB_USER=$DB_USER -e DB_PASSWORD=$DB_PASSWORD -e DB_NAME=$DB_NAME -e DB_PORT=$DB_PORT -e DB_HOST=$DB_HOST -d -p 3000:3000 --name cicd-pipeline-container amagdy9129/cicd-pipeline:latest
    - name: Check Docker Container Status
      run: sudo docker ps -a

