name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker Image
      run: sudo docker pull amagdy9129/cicd-pipeline:latest
    - name: Delete Old Docker Container
      run: sudo docker rm -f cicd-pipeline-container
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:3000 --name cicd-pipeline-container amagdy9129/cicd-pipeline:latest
  