name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Login to Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}        
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Push to Dockerhub
      env:
        IMAGE_NAME: ${{secrets.DOCKER_USERNAME}}/cicd-pipeline
      run: docker push $IMAGE_NAME:latest